Config = {}

Config.Locale = 'en'
Config.MaxSalary = 15000

Config.Inventory = {
    'police',
    'sheriff',
    'fbi',
    'artesh',
    'government',
    'dadgostari',
    'mechanic',
    'taxi',
    'ambulance',
    'digikala',
    'bahama'
}

Config.Armory = {
    ['police'] = {
        'WEAPON_STUNGUN',
        'WEAPON_NIGHTSTICK',
        'WEAPON_BAT',
        'WEAPON_FLASHLIGHT',
        'WEAPON_PISTOL',
        'WEAPON_COMBATPISTOL',
        'WEAPON_SMG',    
        'WEAPON_PISTOL50',
        'WEAPON_HEAVYPISTOL',
        'WEAPON_BAT',
		'WEAPON_SNSPISTOL',
        'WEAPON_SWITCHBLADE',
        'WEAPON_DAGGER',
        'WEAPON_KNUCKLE',
        'WEAPON_ASSAULTRIFLE',
        'WEAPON_BULLPUPRIFLE',
        'WEAPON_SMG_MK2',
        'WEAPON_ASSAULTSMG',
        'WEAPON_MICROSMG',
        'WEAPON_COMBATPDW',
        'WEAPON_CARBINERIFLE',
        --'WEAPON_SHOTGUN',  -- SWAT
        --'WEAPON_SPECIALCARBINE',  -- SWAT
        --'WEAPON_SNIPERRIFLE',  -- SWAT
        --'WEAPON_SMOKEGRENADE',  -- SWAT
    },
    ['sheriff'] = {
        'WEAPON_STUNGUN',
		'WEAPON_BAT',
		'WEAPON_FLASHLIGHT',
		'WEAPON_PISTOL',
		'WEAPON_DOUBLEACTION',
		'WEAPON_COMBATPISTOL',
		'WEAPON_SMG',
		'WEAPON_REVOLVER',
		'WEAPON_HEAVYPISTOL',
		'WEAPON_PISTOL50',
        --'WEAPON_CARBINERIFLE', -- SWAT
        --'WEAPON_SAWNOFFSHOTGUN',  -- SWAT
    },
    ['fbi'] = {
        'WEAPON_PISTOL50',
		'WEAPON_COMBATPISTOL',
		'WEAPON_SMG',
	    'WEAPON_APPISTOL',
        --'WEAPON_CARBINERIFLE', -- SWAT
    },
    ['artesh'] = {
        'WEAPON_COMBATRIFLE',
		'WEAPON_FLAREGUN',
		'WEAPON_SMG',
		'WEAPON_COMBATPISTOL',
		'WEAPON_HEAVYPISTOL',
		'WEAPON_ASSAULTRIFLE_MK2',
		'WEAPON_STUNGUN',
        'WEAPON_NIGHTSTICK',
        'WEAPON_BAT',
        'WEAPON_FLASHLIGHT',
        'WEAPON_PISTOL',
        'WEAPON_COMBATPISTOL',
        'WEAPON_SMG',
        'WEAPON_PISTOL50',
        'WEAPON_HEAVYPISTOL',
        'WEAPON_BAT',
        'WEAPON_SWITCHBLADE',
        'WEAPON_DAGGER',
        'WEAPON_KNUCKLE',
        'WEAPON_ASSAULTRIFLE',
        'WEAPON_BULLPUPRIFLE',
        'WEAPON_SMG_MK2',
        'WEAPON_ASSAULTSMG',
        'WEAPON_MICROSMG',
        'WEAPON_COMBATPDW',
        --'WEAPON_SPECIALCARBINE', price = 0 },  -- SWAT
        --'WEAPON_SHOTGUN', price = 0 },  -- SWAT
        --'WEAPON_MILITARYRIFLE', price = 0 },  -- SWAT
		--'WEAPON_HEAVYSNIPER', price = 0 },  -- SWAT
        --'WEAPON_SNIPERRIFLE', price = 0 },  -- SWAT
        --'WEAPON_SMOKEGRENADE', price = 0 },  -- SWAT
    },
    ['government'] = {},
    ['dadgostari'] = {
        'WEAPON_SMG',
		'WEAPON_COMBATPISTOL',
		'WEAPON_BAT',
		'WEAPON_STUNGUN'
    }
}
Config.Garage = {
    ['police'] = {
        { model = 'admiral', label = 'Motor Aval' },	
		{ model = 'policeb', label = 'Motor Dovom' },		
		{ model = 'policet', label = 'Transporter' },
		{ model = 'pbus', label = 'Otobos Police' },
        { model = 'police', label = 'Police' },
		{ model = 'ghispo2', label = 'Ghispo' },
		{ model = 'policeind', label = 'Neon' },
		{ model = 'rmodgt63police', label = 'GT 63' },
		{ model = 'police5', label = 'Police 5' },
		{ model = 'polgs350', label = 'Lexus' }
    },
    ['sheriff'] = {
        { model = 'admiralsheriff', label = 'Motor Aval' },
		{ model = 'policeb', label = 'Motor Dovom' },
		{ model = 'sheriff', label = 'Mashin Aval' }, 
		{ model = 'sheriff2', label = 'Mashin Dovom' }, 
        { model = 'rmodgt63police', label = 'GT 63' }
    },
    ['fbi'] = {	
		{ model = 'fbi2', label = 'FBI SUV' },
		{ model = 'fbi', label = 'FBI' },
        { model = 'schafter3', label = 'Schafter' },
		{ model = 'policeind', label = 'Neon' },
		{ model = 'schafter5', label = 'Schafter 5' },
		{ model = 'baller5', label = 'Baller' }
    },
    ['artesh'] = {
        { model = 'tiptruck2', label = 'Kamion' },
        { model = 'mule4', label = 'Kamion 2' },
		{ model = 'squaddie', label = 'Squaddie' },
		{ model = 'crusader', label = 'Crusader' },
		{ model = 'insurgent2', label = 'Insurgent 2' },	
		{ model = 'winky', label = 'Winky' },
		{ model = 'riot', label = 'Zed Shoresh' },
        { model = 'barrage', label = 'tir bar' },		
		{ model = 'insurgent3', label = 'insurgent3 ' },
		{ model = 'nightshark', label = 'nightshark ' },
		{ model = 'scarab2', label = 'scarab2 ' },	
		{ model = 'firetruk', label = 'Firetruk' },
		{ model = 'riot2', label = 'Riot 2' },	
		{ model = 'apc', label = 'APC' },
		{ model = 'barrage', label = 'Barrage' },	
		{ model = 'insurgent3', label = 'Insurgent 3' },
		{ model = 'manchez2', label = 'Manchez 2' },	
		{ model = 'xls2', label = 'XLS2' }
    },
    ['dadgostari'] = {
        { model = 'toros', label = 'ghazi' },	
        { model = 'cognoscenti', label = 'ghazi2' },		
		{ model = 'baller4', label = 'scort' },	
		{ model = 'riot', label = 'bus' },
		{ model = 'policeb', label = 'motor' },
		{ model = 'dilettante2', label = 'Guard' }
    },
    ['government'] = {},
    ['ambulance'] = {
        { model = 'fd1', label = 'FD1' },
		{ model = 'fd2', label = 'FD2' },
		{ model = 'fd3', label = 'FD3' },
		{ model = 'fd4', label = 'FD4' },
		{ model = 'madabike', label = 'Motor' },
    },
    ['taxi'] = {
        { model = 'taxi', label = 'Taxi' },
        { model = 'stretch', label = 'Limozin' }
    }
}

Config.MaleDefault = {
    ['bproof_2'] = 0,
    ['helmet_2'] = -1,
    ['chain_2'] = 0,
    ['shoes_1'] = 34,
    ['face_1'] = 0,
    ['age_1'] = 0,
    ['complexion_1'] = 0,
    ['lipstick_4'] = 0,
    ['eyebrows_2'] = 10,
    ['decals_1'] = 0,
    ['glasses_1'] = -1,
    ['arms'] = 15,
    ['bproof_1'] = 0,
    ['makeup_4'] = 0,
    ['hair_color_2'] = 0,
    ['bags_2'] = 0,
    ['watches_1'] = -1,
    ['moles_2'] = 1,
    ['lipstick_3'] = 0,
    ['moles_1'] = 0,
    ['eyebrows_4'] = 12,
    ['arms_2'] = 0,
    ['pants_1'] = 61,
    ['torso_1'] = 15,
    ['torso_2'] = 0,
    ['hair_1'] = 10,
    ['hair_2'] = 0,
    ['hair_color_1'] = 0,
    ['lipstick_1'] = 0,
    ['face_2'] = 21,
    ['beard_3'] = 0,
    ['helmet_1'] = -1,
    ['pants_2'] = 1,
    ['makeup_2'] = 0,
    ['eye_color'] = 0,
    ['mask_1'] = 0,
    ['ears_1'] = -1,
    ['eyebrows_1'] = 0,
    ['glasses_2'] = -1,
    ['bags_1'] = 0,
    ['chain_1'] = 0,
    ['makeup_1'] = 0,
    ['makeup_3'] = 0,
    ['age_2'] = 0,
    ['beard_4'] = 0,
    ['watches_2'] = -1,
    ['complexion_2'] = 1,
    ['decals_2'] = 0,
    ['eyebrows_3'] = 12,
    ['ears_2'] = -1,
    ['face_3'] = 5,
    ['beard_2'] = 10,
    ['tshirt_2'] = 0,
    ['mask_2'] = 2,
    ['beard_1'] = 0,
    ['sex'] = 0,
    ['lipstick_2'] = 0,
    ['tshirt_1'] = 15,
    ['skin'] = 12,
    ['shoes_2'] = 0
}
Config.FemaleDefault = {
    ['bproof_2'] = 0,
    ['helmet_2'] = -1,
    ['chain_2'] = 0,
    ['shoes_1'] = 35,
    ['face_1'] = 0,
    ['arms'] = 15,
    ['complexion_1'] = 0,
    ['lipstick_4'] = 0,
    ['age_1'] = 0,
    ['eyebrows_2'] = 10,
    ['glasses_1'] = -1,
    ['decals_1'] = 0,
    ['bproof_1'] = 0,
    ['torso_2'] = 0,
    ['makeup_4'] = 0,
    ['bags_2'] = 0,
    ['hair_color_2'] = 0,
    ['moles_2'] = 1,
    ['lipstick_3'] = 20,
    ['moles_1'] = 0,
    ['eyebrows_4'] = 12,
    ['arms_2'] = 0,
    ['pants_1'] = 9,
    ['torso_1'] = 16,
    ['watches_1'] = -1,
    ['hair_1'] = 30,
    ['hair_2'] = 0,
    ['hair_color_1'] = 0,
    ['eyebrows_1'] = 1,
    ['face_2'] = 21,
    ['beard_3'] = 0,
    ['helmet_1'] = -1,
    ['pants_2'] = 12,
    ['makeup_2'] = 10,
    ['glasses_2'] = -1,
    ['lipstick_1'] = 3,
    ['ears_1'] = -1,
    ['mask_1'] = 0,
    ['eye_color'] = 0,
    ['bags_1'] = 0,
    ['chain_1'] = 0,
    ['makeup_1'] = 5,
    ['makeup_3'] = 0,
    ['age_2'] = 0,
    ['beard_4'] = 0,
    ['skin'] = 12,
    ['watches_2'] = -1,
    ['decals_2'] = 0,
    ['complexion_2'] = 1,
    ['ears_2'] = -1,
    ['eyebrows_3'] = 26,
    ['beard_2'] = 0,
    ['face_3'] = 6,
    ['mask_2'] = 2,
    ['beard_1'] = 0,
    ['sex'] = 1,
    ['lipstick_2'] = 10,
    ['tshirt_2'] = 0,
    ['tshirt_1'] = 15,
    ['shoes_2'] = 0
}
